expose applyImportMap
systemjs/systemjs pull request #2429
Opened 2022-09-23 09:25 UTC by wenerme

fix #2428

2022-09-23 09:32 UTC, wenerme commented
I don't get the test error, can't find any error messages, running in local seems fine.

2022-09-24 17:00 UTC, guybedford commented
The tests seem to be failing here, can you look into it?

2022-09-25 13:58 UTC, wenerme commented
@guybedford Sorry, but I have no idea why test failed, it's like firefox failed or something, can you have a look ?

2022-09-26 19:50 UTC, guybedford commented
@wenerme for local testing, run `chomp test:browser`. In the Firefox window I'm seeing this error:

![image](https://user-images.githubusercontent.com/598730/192366910-f155d3fc-4308-495f-ae45-7917fdbc7da1.png)

2022-09-27 10:11 UTC, wenerme commented
Running browser test in macos

```bash
CI_BROWSER=/Applications/Firefox.app/Contents/MacOS/firefox chomp test
```

2022-09-27 13:08 UTC, guybedford requested changes
This is looking good, we just need to add some documentation on the method as well to the SystemJS API documentation.

Also, in terms of the API name, how about `addImportMap` instead of `applyImportMap`? That would also match the corresponding methods in the ES module shims project (https://github.com/guybedford/es-module-shims#reading-current-import-map-state)

2022-09-27 13:31 UTC, wenerme commented
`add` more precisely, renamed to addImportMap, add some doc about addImportMap

2022-09-27 13:35 UTC, guybedford approved these changes
Looks great, thanks for working on this.

Note in es module shims we explicitly avoid overrides when doing this per https://github.com/guybedford/es-module-shims#overriding-import-map-entries, with overrides explicily enabled via configuration. Worth noting but perhaps SystemJS doesn't need this as much.

2022-09-27 13:35 UTC, guybedford commented on docs/import-maps.md
> +Standard import map is based on dom operation, for SystemJS, you can use `System.addImportMap` to add import map dynamically for browser and node.
Perhaps something like:

```suggestion
To dynamically add import maps, a non-spec API is available to extend additional mappings into the import map at any time:
```

2022-09-27 14:03 UTC, guybedford commented on docs/api.md
> +Allows you to add import-map without DOM interop.
```suggestion
Allows adding an import map without using the DOM.
```

2022-09-27 14:03 UTC, guybedford commented on docs/import-maps.md
> +> This may override existing import maps, for more details, please check https://github.com/guybedford/es-module-shims#overriding-import-map-entries
```suggestion
> Non-standard Extension
```

2022-09-27 14:03 UTC, guybedford commented on docs/import-maps.md
> +To dynamically add import maps, a non-spec API is available to extend additional mappings into the import map at any time:
```suggestion
The `addImportMap` method is available to dynamically extend additional mappings into the import map at any time:
```

2022-09-27 14:03 UTC, guybedford commented on docs/import-maps.md
> +```
```suggestion
```

Any existing map entries will be overridden with the new values.
```

2022-09-27 14:04 UTC, guybedford commented on docs/import-maps.md
> +
```suggestion

```suggestion

Any existing map entries will be overridden with the new values.
```

2022-09-27 14:05 UTC, merged